### ISSUE TITLE
Not an issue - question on out of the box use case

### ISSUE THREAD

**Issue by johndpope** [autonomousvision/stylegan_xl#1]
basically had this idea to use this technology to take a pdf document and upgrade it to a higher quality.
Like a picture that's bad quality - I want to boost the quality of music score.

if you see the artifacts here / blacks are bad - etc I want a neural net to reimagine the document - not merely boost contrast.

<img width="2048" alt="Screen Shot 2022-02-03 at 10 19 04 pm" src="https://user-images.githubusercontent.com/289994/152333255-2a84754f-b861-49ff-9e45-92968f73dd61.png">

Could it just be a case of training with higher quality docs (using this library) - then sending in an image and finding the latent?

**Comment by xl-sr** [comment]
What an interesting idea! I actually gave it a go with the current 1024 model.

**After Latent optimization**
<img src="https://user-images.githubusercontent.com/29833625/152402770-3e060e4a-b502-4d97-bbbe-31677a7a7fd0.png" height="400">

**After PTI**
<img src="https://user-images.githubusercontent.com/29833625/152401496-6e5314c8-45f1-4efd-8227-a94f5f68297b.png " height="400">

You can see that the latent optimization yields unsatisfying results which are expected because the input is somewhat out of domain. I am actually surprised that it does not look terrible. When running PTI (while disabling regularization, so using StyleGAN-XL as deep image prior), you can reconstruct the input faithfully, longer training would prob. give even sharper results. However, it also partially reconstructs the artifacts.


These results are of course not very surprising. But, if you have a good amount of high-quality docs to train the model on, this will work much better. Something else you can try is to use an image restoration network, e.g. [SwinIR](https://github.com/JingyunLiang/SwinIR) which is good for removing jpeg artifacts and might also work for you. Another thing to try is downsampling the image and then upsample it again with a superresolution network, SwinIR also has an option for that. A similar trick works well for face reconstruction (https://github.com/autonomousvision/projected_gan/issues/25#issuecomment-1004265606)

**Comment by johndpope** [comment]
thanks for quick response. some nice avenues to explore.
